### ISSUE TITLE
Use of aliases and extending VCs

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-imp-guide#10]
The data model provides no guidance as to whether the short form aliases for properties should be used, may be used or must be used. Is it OK to use IRIs throughout? In addition, if I extend a VC with some new terms, is it OK to only use IRIs and to not produce a new @context value? Or does a new type of VC require a new @context value

**Comment by dlongley** [comment]
> Is it OK to use IRIs throughout?

I think that should be ok, yes.

> In addition, if I extend a VC with some new terms, is it OK to only use IRIs and to not produce a new @context value? Or does a new type of VC require a new @context value

I also think that should be ok. We should spell out how to do it the other way and recommend it, but indicate it's not required.

**Comment by TallTed** [comment]
The point of `@context` is to link simple-literal aliases to IRIs, so using IRIs throughout a given VC obviates the need for `@context` in that VC.

**Comment by burnburn** [comment]
See answer and next steps in issue #16.  Closing.
