### ISSUE TITLE
Add section detailing how to author a new VC (semantics and schema)

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-imp-guide#16]
See #9.

**Comment by dlongley** [comment]
Ensure that an example with a simple alias and a link to the JSON-LD spec is added and also mention that IRIs can be used instead of aliasing. See: #10.

**Comment by dlongley** [comment]
I recommend this be closed now that #18 has been merged.

**Comment by TallTed** [comment]
@dlongley - #18 has not yet been merged (as I checked that before making my many comments on it just now...)

**Comment by dlongley** [comment]
@TallTed, oh, you're right, my comment should have said: When #18 is merged, I recommend we close.

**Comment by deiu** [comment]
This issue has been resolved by merging #18
