### ISSUE TITLE
Add guidance to prevent unauthorized credential reuse by verifiers

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c/vc-imp-guide#2]
Original issue: https://github.com/w3c/vc-data-model/issues/203
> If a credential may be delegated from one holder to another, what prevents a verifier from taking a presentation and pretending they are a delegated holder?

Add a section to the implementation guide about preventing unauthorized credential reuse by verifiers. To put it another way, add recommended mechanisms to prevent the stealing of credentials by verifiers (and impersonation of the subject).

Example existing mechanisms:

* `aud`ience restriction (from the [OAuth2 Threat Model and Security Consideration](https://tools.ietf.org/html/rfc6819) document)
* Use of the "subject only" Terms of Use property
* others

**Comment by brentzundel** [comment]
The signature we use for zkps also prevent this.

**Comment by dlongley** [comment]
We should add examples of various proof methods and the mechanisms they include for targeting VPs at various domains, etc.

**Comment by deiu** [comment]
Hi @dlongley and @brentzundel! Any chance you can start adding those examples in a PR soon, even if it's just WIP for now? Thanks a bunch! 😄

**Comment by David-Chadwick** [comment]
Using the nonTransferrable property is a good way of ensuring that only the subject can present the VC to anyone, and stops the recipient (who ever it is) from passing it on. I am proposing to use this property in mDL, and we are using this in our implementation, as most people I have talked to require it.

**Comment by TallTed** [comment]
Except that the nonTransferrable property doesn't *prevent* Presentation by non-original Holders, nor any Holder from "passing it on."

It *advises* Verifiers that they ought not accept the VC from anyone but the original Holder (who is not necessarily the Subject), and it *might* (if a Holder looks inside) *advise* Holders that they ought not pass the VC to any other Holder, nor (if they receive it from the original Holder) Present it to a Verifier.

**Comment by David-Chadwick** [comment]
> Except that the nonTransferrable property doesn't _prevent_ Presentation by non-original Holders, nor any Holder from "passing it on."
> 

Correct. Any one can do whatever they want to do. All we are concerned about is defining standard's conforming behaviour, not non-standard's conforming behaviour (since there are an infinite variety of such behaviours).


> It _advises_ Verifiers that they ought not accept the VC from anyone but the original Holder (who is not necessarily the Subject), and it _might_ (if a Holder looks inside) _advise_ Holders that they ought not pass the VC to any other Holder, nor (if they receive it from the original Holder) Present it to a Verifier.

This is where we disagree. The standard says a VP created by anyone other than the subject is invalid. So a standard's conforming verifier should not accept any invalid VC or VP (and there are several data model properties that indicate whether a VC is valid or invalid). A verifier can clearly accept any invalid VC or VP if it wants to, but this is non-conformant behaviour, so we do not care about it.

**Comment by TallTed** [comment]
And again, *this standard* is a *data model*.  *All actions* on that data model fall under *protocol.*  Being non-normative, the Implementation Guide can only provide *guidance* and *advice,* it *cannot* get into what is "conforming behavior."

Also, a VP *may* be created by Holders who are not the Subject -- e.g., a Pet's Owner, or a Child's Parent -- or the whole spec is broken as it stands, and all sorts of fireworks are about to go off.
