### ISSUE TITLE
variable vocab is being discussed as if invariable

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-imp-guide#22]
>> `We don't want them to have to worry about terms being redefined` 
>> `in unexpected ways. That way their software can inspect only the` 
>> `<code>@context</code> values and then be hard coded to understand`
>> `the meaning of the terms.`
>
> This basically says, "we want them to act as if the definition of those terms is immutable" even as we're saying "the definition of these terms might change."
>
> That's not OK!

Anything that's being hard-coded SHOULD (and I really want this to be MUST) be based on something that's immutable.  The meaning of `schema:name` _might_ change between VC creation and verification, and *that's* a problem.

If the `@context` were hashlinked, that might be a solution.

Or the example could be based on a static, immutable vocab that we include with this guide.

See comment threads in #18

**Comment by brentzundel** [comment]
I share this concern

**Comment by deiu** [comment]
I will add some text mentioning best practices re. schema.org.

**Comment by TallTed** [comment]
> I will add some text mentioning best practices re. schema.org.

The concern is not focused on schema.org, per se, but on _any third party vocabulary,_ over which neither issuer, holder, nor verifier may have any control, and which may change between VC creation and verification.

**Comment by dmitrizagidulin** [comment]
(Adding this link in case it's helpful, [pr 272 to the DID spec](https://github.com/w3c-ccg/did-spec/pull/272/files) discusses vocab versioning.)

**Comment by deiu** [comment]
Thanks for the pointer, @dmitrizagidulin!

**Comment by deiu** [comment]
I've opened PR #54 for this issue.
