### ISSUE TITLE
examples allow copying non-JSON elements

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-imp-guide#29]
The examples in the implementation guide should allow for the same magic as the data model where non-JSON elements such as comments can't be selected.

**Comment by dlongley** [comment]
The CSS for this is already in the implementation guide, the examples just need to be updated to wrap comments in a span with the `comment` class. Here's an example:

```
"verifiableCredential": { <span class="comment">...</span> },
```

https://github.com/w3c/vc-imp-guide/blob/gh-pages/index.html#L373
