### ISSUE TITLE
Selective Disclosure

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-imp-guide#42]
The current guide suggests two ways of performing selective disclosure.
The mobile driving license ISO working draft specifies a third way: release one VC where all the subject property values are hashes. The holder then releases the VC with the clear contents of the properties s/he wants to disclose, and the verfier can compute the hash to validate the value is correct. Shall we add this as well?

**Comment by jonnycrunch** [comment]
@David-Chadwick this seems vulnerable to a simple dictionary brute force attack unless you add a nounce or aggregate the VC object section.

**Comment by David-Chadwick** [comment]
No, because they have different nonces with each property value, each nonce being at least 16 bytes long

**Comment by David-Chadwick** [comment]
The text to describe this is in PR#47

**Comment by TallTed** [comment]
@David-Chadwick -- Note that `PR #47` will auto-link to the PR, while `PR#47` will not.

i.e. -- See PR #47
