### ISSUE TITLE
Section 7.2 Issues 

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-imp-guide#45]
There is the table in 7.2 Benefits of JSON-LD and LD-Proofs where it states and X in the Designed to easily support experimental signature systems field, as JWTs allow usage of non-registered signatures to be used, via Collision-Resistant Name.
Also has an X in the Canonicalization requires only base-64 encoding for JWT, this is also not correct

**Comment by dlongley** [comment]
The group agreed that a proponent for each proof mechanism would write a proof advantages/disadvantages section and that we would accept conflicting points of view. Recommendations are invariably biased and this was the best that the group could come up with; please note that the proponents of the non-JWT mechanisms disagree with some of what is being claimed in the JWT section as well.

**Comment by jricher** [comment]
As per RFC7515, this is technically allowed to be a URI:

> "alg" values
   should either be registered in the IANA "JSON Web Signature and
   Encryption Algorithms" registry established by [JWA] or be a value
   that contains a Collision-Resistant Name.  The "alg" value is a case-
   sensitive ASCII string containing a StringOrURI value.  This Header
   Parameter MUST be present and MUST be understood and processed by
   implementations.

That said, I have never seen a value in the wild that is not a registered JWA value, and I would figure that most implementations would break on this being an unknown. And by "break" here I mean "refuse to process the signature", which is the appropriate response.

**Comment by awoie** [comment]
uPort is supporting the non-registered value for `alg` (= `ES256K-R`) that indicates that secp256k1 signatures were used with an additional recovery bit. This could be seen as experimental.

**Comment by jricher** [comment]
@awoie That usage is off-spec, as it is neither a registered value nor a collision-resistant name, which is defined as:

>    Collision-Resistant Name
      A name in a namespace that enables names to be allocated in a
      manner such that they are highly unlikely to collide with other
      names.  Examples of collision-resistant namespaces include: Domain
      Names, Object Identifiers (OIDs) as defined in the ITU-T X.660 and
      X.670 Recommendation series, and Universally Unique IDentifiers
      (UUIDs) [RFC4122].  When using an administratively delegated
      namespace, the definer of a name needs to take reasonable
      precautions to ensure they are in control of the portion of the
      namespace they use to define the name.

To be compliant with the JWS specification, uPort should register its algorithm value with the JWA registry.

**Comment by deiu** [comment]
Am I correct to assume that this issue is not about the Implementation guide itself, but rather about uPort's choice of an unregistered JWT value?

@jricher, I would like to suggest that you open a similar issue in one of uPorts repos instead.

**Comment by awoie** [comment]
@jricher Thanks for calling that out. I agree that this should be a registered IANA alg. We haven't had time to do that yet but it is on our agenda.

**Comment by jricher** [comment]
The common compact of JWT using JWS/JWE uses only Base64URL for canonicalization purposes. Other encodings for JWT are possible which can use different mechanisms.  The only text in RFC7519 that refers to the compact serializations is non-normative, but declarative.

**Comment by deiu** [comment]
> The common compact of JWT using JWS/JWE uses only Base64URL for canonicalization purposes. Other encodings for JWT are possible which can use different mechanisms. The only text in RFC7519 that refers to the compact serializations is non-normative, but declarative.

The group has reached the conclusion that @jricher's comment has adequately addressed the issue at hand and no action is necessary on our part.
