### ISSUE TITLE
Suggestions on how to do progressive trust or graceful degredation

### ISSUE THREAD

**Issue by stonematt** [w3c/vc-imp-guide#6]
Issue added from discussion in Barcelona F2F: https://www.w3.org/2019/03/05-vcwg-minutes.html
add suggestions on how to do progressive trust or graceful degredation

See discussion in https://github.com/w3c/vc-data-model/issues/222

**Comment by burnburn** [comment]
@brentzundel can you still take/lead this?

**Comment by deiu** [comment]
Has pending PR #14

**Comment by brentzundel** [comment]
PR #14 is ready for review

**Comment by brentzundel** [comment]
PR is merged, closing this Issue
