### ISSUE TITLE
Add sections outlining benefits of different syntax + proof formats

### ISSUE THREAD

**Issue by msporny** [w3c/vc-imp-guide#8]
Decision from F2F Barcelona:
A proponent for each format will write a section in the implementation guide describing the format. 
- JSON-LD proofs (Manu)
- JSON-LD + JWT and JSON + JWT (Oliver)

To do:
- [x] @msporny will write the section on LD Proofs
- [x] @awoie will write the section on JSON-LD + JWT and JSON + JWT
- [x] @ken-ebert will write the section on ZKPs

**Comment by BigBlueHat** [comment]
Think the wording for PF19 could use some rewording or alternate checkboxing.

It currently reads...
> PF19. Canonicalization requires more than base-64 encoding.

which, given what's mentioned in [PF19](https://w3c.github.io/vc-imp-guide/#pf19) the checkboxes seem backwards as LD-Proofs requires more than base-64 encoding.

**Comment by burnburn** [comment]
PR #12 was only a partial fix for this issue.  More work needed.

**Comment by burnburn** [comment]
@awoie waiting on your section
