### ISSUE TITLE
@context value ordering

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-imp-guide#9]
The data model says that @context values must be in order, but as a JSON implementor I do not appreciate the reason nor requirement for this. An explanation in the implementation guide is needed

**Comment by dlongley** [comment]
A JSON-LD processor cares about the order, defining terms (and allowing overrides) using a "last wins" order. Of course, we are recommending people use the JSON-LD 1.1 `@protected` terms feature that prevents term overrides, but I think it would be simpler to tell everyone the same thing and to keep the order the same everywhere. I agree we should state this in the implementation guide.

**Comment by dlongley** [comment]
In the section that describes how to author a new VC (its actual semantics and schema, etc.) we must link to the JSON-LD spec to describe how contexts are created/work and the required order of contexts for VCs.

**Comment by burnburn** [comment]
Replaced by #16.  Closing.
